on: [push]

jobs:
  hello_world_job:
    runs-on: ubuntu-latest
    name: Generate the MD files
    steps:
      # To use this repository's private action, you must check out the repository
      - name: Checkout
        uses: actions/checkout@v2
      - name: Generate MD files
        uses: ./ # Uses an action in the root directory
        id: hello