on: [push]

jobs:
  hello_world_job:
    runs-on: ubuntu-latest
    name: Generate MD files
    steps:
      # To use this repository's private action, you must check out the repository
      - name: Checkout
        uses: actions/checkout@v2
      - name: Generate MD files Step
        uses: ./ # Uses an action in the root directory
        id: generate_file
      # Use the output from the `hello` step
      - name: Get the list of files
        run: echo "The files are ${{ steps.generate_file.outputs.files }}"
      - name: display the file content
        run: echo "The contents of the file is ${{ steps.generate_file.outputs.content }}"
